name: auto_mobile_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  get_it: ^7.1.3
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.22.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  flutter_rating_bar: ^4.0.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  build_runner: ^2.0.4



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Black.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Bold.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Heavy.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Heavy-1.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Light.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Light-1.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Medium.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Medium-1.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Regular.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Regular-1.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Semibold.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Thin.ttf
        - asset: assets/fonts/FontsFree-Net-SFProDisplay-Ultralight.ttf